### ISSUE TITLE
Unable to upload files

### ISSUE THREAD

**Issue by MistakingManx** [pmt-mcpe-fun/legacy-website#32]
I've uploaded all the files in https://github.com/pmt-mcpe-fun/legacy-website
to http://pmt.manx7.org/
could you help me figure out why I cannot use the 'choose file' button?

(i don't share pmt.manx7.org with anyone, it's for personal use)
_sorry I don't understand it_

**Comment by nathfreder** [comment]
Hi, we were just chatting on Twitter. Sorry for missing this issue, I didn't even know this repository was still in use.
